name: GitHub Action For Resume
on:
    push:
      branches:
        - main
        - isaacreal
    pull_request:

jobs:
  HostedActions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm install
      - name: Create dir
        run: |
          #!/bin/bash
          export
          sudo apt update
          sudo apt install -y pandoc
          mkdir ./output || true
      - run: npm run generatepdf
        timeout-minutes: 5
      - name: Generate Docx
        run: |
          ./genDocx.sh
        timeout-minutes: 5
      - uses: actions/upload-artifact@v3
        with:
          name: resumeDocx
          path: resume.docx
      - uses: actions/upload-artifact@v3
        with:
          name: resumePDF
          path: output/resume.pdf
      - name: Check out my other private repo
        uses: actions/checkout@v4
        with:
          repository: idjohnson/idjohnson
          token: ${{ secrets.my_pat }}
          path: 'idjohnson'
      - name: debug
        run: |
          set -x
          cd $GITHUB_WORKSPACE/idjohnson
          git config --global user.email "isaac.johnson@example.com"
          git config --global user.name "Isaac Johnson"
          cp ../resume.docx ./
          cp ../output/resume.pdf ./
          git add resume.docx
          git add resume.pdf
          git commit -m 'add resume'
          git push